
title: My Resume
url: 'https://www.aqeelainstruments.com/'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Sugeng Riyanto  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: Tangerang Selatan , Indonesia


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: https://twitter.com/srphysics04 ## your twitter account url
linkedin: https://www.linkedin.com/in/sugeng-riyanto-8322a945/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
